### ISSUE TITLE
border padding around main visualization window, not going away in fullscreen

### ISSUE THREAD

**Issue by altineller** [ros2/rviz#1024]
Hello,

How can I make the border around main visualzation window go away? Or change its color if we cant make it go away.
When in full screen it apppears as a 8-9px white border.

I understand that there is no setting or customization for this, and I already have built rviz from source to get the default full screen launch going, and now I would like to remove the border or at least set it color to black. 

Which part of code is responsible for this? I have been reading the source code, and could it be the border of a remote library or object?

Any ideas/help greatly appreciated.

Best Regards,
C.A.

**Comment by clalancette** [comment]
Unfortunately, we don't have a great idea on how to do this.  Likely this has something to do with the Qt settings or the theme, but I'm not sure.  If you do figure something out, please feel free to update here or open a PR to improve things.

**Comment by altineller** [comment]
@clalancette  I think it has to do with te OgreRenderWindow.h, which is at ./ros/humble/opt/rviz_ogre_vendor/include/OGRE/OgreRenderWindow.h

**Comment by bochen87** [comment]
> @clalancette I think it has to do with te OgreRenderWindow.h, which is at ./ros/humble/opt/rviz_ogre_vendor/include/OGRE/OgreRenderWindow.h

How did you solve this issue?

Edit: I found the issue, made a PR #1228  - Would be great if this could also be released into jazzy!
