### ISSUE TITLE
RVIZ_RENDERING_PUBLIC for class member functions

### ISSUE THREAD

**Issue by felixf4xu** [ros2/rviz#1069]
Hi,

In Windows dll, `RVIZ_RENDERING_PUBLIC` is used to export class or functions. For class member functions, I see 2 different ways to use `RVIZ_RENDERING_PUBLIC` in rviz2 code. 

One  way is to export the whole class (therefor export all member functions), like https://github.com/ros2/rviz/blob/rolling/rviz_rendering/include/rviz_rendering/material_manager.hpp#L47
```hpp
class RVIZ_RENDERING_PUBLIC MaterialManager
{
}
```

The other way is to only export selected member functions, like https://github.com/ros2/rviz/blob/rolling/rviz_rendering/include/rviz_rendering/render_system.hpp#L66
```hpp
class RenderSystem
{
public:
  RVIZ_RENDERING_PUBLIC
  static
  RenderSystem *
  get();

  ...
  void
  prepareOverlays(Ogre::SceneManager * scene_manager);
```
In the code above, both `get()` and `prepareOverlays()` are public member functions but only `get()` is exported. I'm not sure why and I'd like to check if the design could be changed.

In my case, I'm building some code in Windows and the code uses `prepareOverlays()`:

```cpp
rviz_rendering::RenderSystem::get()->prepareOverlays(manager);
```

In my case, the `get()` function can be linked but `prepareOverlays()` has link error. I think I have 2 options to fix it, to export one additional function of `prepareOverlays()` or to export the whole `RenderSystem` class. 

I'd like to seek some comments here.

**Comment by clalancette** [comment]
> I'm not sure why and I'd like to check if the design could be changed.

I don't think we have a set design for this; we usually use whatever works.  I know in the past I've personally had some problems with exporting entire classes, and in those cases exporting the individual methods works.  But I've never dug into the details of why that is.

In any case, we'd be happy to take a patch which exported either the class or the individual method, as long as it continues to build, link, and run on Windows.
