### ISSUE TITLE
rviz_rendering build fail cause rviz_ogre_vendor::OgreMain-NOTFOUND

### ISSUE THREAD

**Issue by yechun1** [ros2/rviz#108]
I try to build rviz 2 but fail while build rviz_rendering, rviz_ogre_vendor::OgreMain-NOTFOUND. Does any one meet this issue

# build log
root@robot2:~/ros2_ws/rviz_ws/rviz2# ament build
+++ Building 'rviz_rendering'
==> '. /root/ros2_ws/rviz_ws/rviz2/build/rviz_rendering/cmake__build.sh && /usr/bin/make cmake_check_build_system' in '/root/ros2_ws/rviz_ws/rviz2/build/rviz_rendering'
==> '. /root/ros2_ws/rviz_ws/rviz2/build/rviz_rendering/cmake__build.sh && /usr/bin/make -j8 -l8' in '/root/ros2_ws/rviz_ws/rviz2/build/rviz_rendering'
[  8%] Automatic moc for target rviz_rendering
[  8%] Automatic moc for target rendering_example
[  8%] Built target rendering_example_automoc
[  8%] Built target rviz_rendering_automoc
[ 86%] Built target rviz_rendering
CMakeFiles/rendering_example.dir/build.make:123: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/rendering_example.dir/all' failed
make[1]: *** [CMakeFiles/rendering_example.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

# check the build.make 
find several modules "NOTFOUND"
cat build/rviz_rendering/CMakeFiles/rendering_example.dir/build.make
rendering_example: rviz_ogre_vendor::OgreMain-NOTFOUND
rendering_example: rviz_ogre_vendor::OgreOverlay-NOTFOUND
rendering_example: rviz_ogre_vendor::RenderSystem_GL-NOTFOUND
rendering_example: rviz_ogre_vendor::OgreGLSupport-NOTFOUND

**Comment by greimela-si** [comment]
This error seems to occur when the CMake build type is not the same for all packages.

Can you try the following steps?
- Delete the `build` and `install` folder of your rviz workspace
- Build and explicitly provide the build type: 
  `ament build --cmake-args -DCMAKE_BUILD_TYPE=<Debug|Release>`

**Comment by yechun1** [comment]
`ament build --cmake-args -DCMAKE_BUILD_TYPE=<Debug|Release>`, could pass this build. 

But `ament build `without CMAKE_BUILD_TYPE=<Debug|Release> will fail. Also provide `CMAKE_BUILD_TYPE=RelWithDebInfo ` fails. 
Check cmake code` Source/cmTarget.cxx`, no IMPORTED_LOCATION_ and IMPORTED_CONFIGURATION to find rviz_ogre_vendor::OgreMain library.

Set `IMPORTED_CONFIGURATIONS=RELEASE|DEBUG` could fix the issue. 

(Patch: Fix OgreMain-NOTFOUND when build rviz_rendering #109 )

**Comment by yechun1** [comment]
Root Cause: 
Not `set_target_properties `for `IMPORTED_LOCATION_NOCONFIG` in `rviz_ogre_vendorConfig.cmake.in`, so that cmake could not find the library. 


Solution:
-  First delete the `build `and `install `folder, 
then build with `ament build --cmake-args -DCMAKE_BUILD_TYPE=<Debug|Release>`

-  Or set `IMPORTED_CONFIGURATION ` and just apply the patch #109 , build with "ament build" could work.

**Comment by yechun1** [comment]
Patch  #109 merged, close this issue.
