### ISSUE TITLE
rviz black screen, mesa upgrade not possible

### ISSUE THREAD

**Issue by Robeatrice** [ros2/rviz#1081]
Hello I also have the issue of only seeing a black screen when using rviz over the docker. I wanted to try upgrading the mesa package but the upgrade didn't work. I get the Error: 
dpkg: error processing package linux-image-6.2.0-36-generic (--configure):
installed linux-image-6.2.0-36-generic package post-installation script subprocess returned error exit status 1
Errors were encounternt while processing:
linux-image-6.2.0-36.generic 
E: Sub-process /usr/bin/dpkg returned an error code (1)

Unfortunately I don't know how to fix that and I cound't find something helpfull on the internet. Can someone help me?
Thank you very much!

              I also had this problem with windows 10 enterprise, docker-desktop and Ubuntu 22.04 LTS. I was able to fix this issue by upgrading the mesa package with the binaries provided by the kisak/kisak-mesa ppa:

> add-apt-repository ppa:kisak/kisak-mesa 
> apt update
> apt upgrade

_Originally posted by @Stefan-working in https://github.com/ros2/rviz/issues/948#issuecomment-1427569107_

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
