### ISSUE TITLE
Effort display seg fault when no effort limit is specified in URDF

### ISSUE THREAD

**Issue by roncapat** [ros2/rviz#1083]
https://github.com/ros2/rviz/pull/990 by @ahcorde introduced Effort display.
However in these lines:
https://github.com/ros2/rviz/blob/01df29780a7d90917b9d927bf09a931d1e57f223/rviz_default_plugins/src/rviz_default_plugins/displays/effort/effort_display.cpp#L197-L200
`limit` is not checked and might be `nullptr`.
This IMHO shall be handled: the user shall get a warning that the joint has no associated effort limit in URDF but this is required for visualization. Maybe the joint can be skipped (i.e. not inserted in the tree in the plugin sidebar).

**Comment by clalancette** [comment]
Yep, agreed.  A pull request to fix the crash would be welcome.
