### ISSUE TITLE
Feature Request: Reset hotkey

### ISSUE THREAD

**Issue by paulerikf** [ros2/rviz#1089]
Note: Not sure about etiquette here, I made a draft PR #1088, but making an issue as well in case of discussion.

------------------------

I find myself often wishing there was an easier way to easily "reset" rviz. I prefer to work with rviz in full-screen mode which exasperates the issue (as one must first minimize rviz, then click reset, then go back to full-screen).

In case I'm not the only one who would like a reset hotkey, I made a draft PR #1088 to make the "R" key a hotkey for `resetTime` (the function called by the "Reset" button).

**Comment by clalancette** [comment]
Closing since we merged in #1088
