### ISSUE TITLE
segment fault when writing a display plugin.

### ISSUE THREAD

**Issue by yang19900808** [ros2/rviz#1115]
I wtite a custom display plugin to meet my individual needs in the following way.
`class CustomPointCloud2Display : public rviz_default_plugins::displays::PointCloud2Display`
`{`
`public:`
`  CustomPointCloud2Display();`
`public:`
`  void onDisable() override;`
`protected:`
`  void onEnable() override;`
`  void timerEvent(QTimerEvent *event) override;`
`private:`
`  int32_t m_timer_event_id {-1};`
`  bool m_first_second {true};`
`  uint32_t m_messages_received_last_second {0U};`
`  uint32_t m_tmp_messages_received {0U};`
`};`

The plugin works well but when it quit the rviz2, a segment fault appears.
I paste the stack info here, can any one tell me how to fix or avoid this issue?
![image](https://github.com/ros2/rviz/assets/45547893/31da94cb-5bf9-48ab-922b-99aaf2555229)

**Comment by clalancette** [comment]
This is a difficult one to tell.  Also, Foxy is End-of-Life.

What I'm going to suggest here is that you retry your plugin with Humble.  If you are still seeing the crash, then I'd suggest reopening this issue and post the complete code for your plugin.  That will help debug it.
