### ISSUE TITLE
ESC to switch to default tool not working in humble.

### ISSUE THREAD

**Issue by Krzo99** [ros2/rviz#1119]
In Rviz2, switching between tools with shortcuts works normally. 
However, pressing ESC to switch back to the default tool doesn't work. 

This error also happens, when I try to process keyPressEvent in a custom panel widget. When focused, normal keys work, but the ESC key is not captured. However, if I hold down the mouse button and press ESC, it is captured (using a custom eventFilter on QApplication.

```cpp
class ESCKeyPressFilter : public QObject {
    Q_OBJECT
protected:
    bool eventFilter(QObject *obj, QEvent *event) override {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
            if (keyEvent->key() == Qt::Key_Escape) {
                emit ESCPressed();
                return true;
            }
        }
        return QObject::eventFilter(obj, event);
    }

signals:
    void ESCPressed();
};

....

auto app = QApplication::instance();
    if (app != nullptr) {
        ESCKeyPressFilter *filter = new ESCKeyPressFilter();
        app->installEventFilter(filter);

        connect(filter, &ESCKeyPressFilter::ESCPressed, this, &TerrascoutPanel::onESCPressed);
    }

    setFocusPolicy(Qt::StrongFocus);
```

It looks like ESC key is being handled somewhere else. The only thing I could find is the "exit fullscreen" shortcut in visualization_frame.cpp

`new QShortcut(Qt::Key_Escape, this, SLOT(exitFullScreen()));`

Could this line be interrupting other ESC key presses?

My version of rviz2: `ros-humble-rviz2/jammy,now 11.2.9-1jammy.20231207.081716 amd64`

**Comment by audrow** [comment]
Hi @Krzo99, it's strange that it's not working. I wonder if you're right about the line. 

If you have time, feel free to dig into this further and open a PR if you find a fix.

**Comment by Krzo99** [comment]
I'll look into it when I have time, which I'm not sure when it'll be.
Keep you updated!

Update: The line `new QShortcut(Qt::Key_Escape, this, SLOT(exitFullScreen()));` is the culprit, when removed, the ESC key correctly switches selected tool back to default one.

**Comment by marip8** [comment]
This was solved several years ago in the ROS1 Rviz: https://github.com/ros-visualization/rviz/pull/1416. We could probably apply the same patch here fairly easily
