### ISSUE TITLE
Wierd subscription rates

### ISSUE THREAD

**Issue by ahcorde** [ros2/rviz#1144]
I have an image suscriber publishing at 25 Hz. When I run `ros2 topic hz` I can see that the node is publishing the images fine.

```bash
ros2 topic hz /color/image_raw 
average rate: 23.069
	min: 0.032s max: 0.084s std dev: 0.01428s window: 25
average rate: 21.020
	min: 0.032s max: 0.285s std dev: 0.03701s window: 48
```

But When I use the Camera or Image plugin I can only see ~5-8 Hz. But it's even more wierd if I open a `ros2 topic echo` on the same topic. I'm able to reach ~11-12 Hz.

any thoughts on this @clalancette ?

**Comment by Yadunund** [comment]
>But When I use the Camera or Image plugin I can only see ~5-8 Hz

When you say "see", are you referring to the printout added in https://github.com/ros2/rviz/pull/1113? If so, could you check if the frequency matches more closely when you uncheck and check the topic in the Display panel? (ie, disable and enable subscription).
