### ISSUE TITLE
No depthcloud plugin for rviz2 galactic!

### ISSUE THREAD

**Issue by ftaheri** [ros2/rviz#1147]

**Comment by clalancette** [comment]
Galactic is End-of-Life now, so we won't be making any more updates to it.  We encourage you to move to ROS 2 Humble or later, which are still supported.

**Comment by ftaheri** [comment]
Hello Chris,
We are using galactic in our research, and we cannot move to humble now. I would appreciate any guidance you can provide.


Thank you!
Best,
Fatemeh 





Get Outlook for iOS
