### ISSUE TITLE
Inertia visualization missmatch between rviz and gazebo

### ISSUE THREAD

**Issue by ottojo** [ros2/rviz#1170]
Following the [NAV2 tutorial](https://navigation.ros.org/setup_guides/urdf/setup_urdf.html), the equivalent-box inertia display in rviz `RobotModelDisplay` shows unexpected visualization, while gazebo shows inertia box equivalent to model:

![2024-03-14_21-37](https://github.com/ros2/rviz/assets/7536298/871445b7-b568-4099-8cb9-33649d98735f)
![2024-03-14_21-41](https://github.com/ros2/rviz/assets/7536298/e06652aa-00e7-4f65-a2d2-5fe2e738baf7)

When removing the rotation in `<inertia><origin>`, both show the box as rviz does, so i guess rviz does not take that rotation into account while gazebo does.

URDF:

```xml
<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Define robot constants -->
    <xacro:property name="base_width" value="0.5"/>
    <xacro:property name="base_length" value="1.0"/>
    <xacro:property name="base_height" value="0.18"/>

    <!-- Define intertial property macros  -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0"
                     izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>

        <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>
</robot>
```

**Comment by MrKeith99** [comment]
I am experiencing the same problem in Humble.
My current Rviz2 version is `ros-humble-rviz2=11.2.14-1jammy.20241128.060321`

![Screenshot from 2024-12-24 15-47-37](https://github.com/user-attachments/assets/a012aaea-d516-4f5d-82aa-879f556b43ce)

I was wondering if the PR (https://github.com/ros2/rviz/pull/1171) could be merged into the `humble` branch and allow its  binary installation as well.

Thank you!
