### ISSUE TITLE
libGL error: failed to create drawable after installing Torch in same environment

### ISSUE THREAD

**Issue by rubenponsaers** [ros2/rviz#1189]
Hello, yesterday when I was working on my ROS2 project I had to install torch to perform some object detection and visualize it in rviz2. I saw that torch uninstalled some lib... package and installed a newer version. I do not know however which version this was. However, afterwards, rviz2 starts crashing with the message 'libGL error: failed to create drawable'.

The error looks like this:
![Screenshot from 2024-04-22 17-08-52](https://github.com/ros2/rviz/assets/36641865/9bf446c0-817b-4ad8-8014-20410d7e4922)

I am running Ubuntu 2.20 with 
![image](https://github.com/ros2/rviz/assets/36641865/28729afe-6579-4aa3-a6d3-ef322427f263)

Thanky you in advance for helping me!

**Comment by rubenponsaers** [comment]
UPDATE: after setting the rviz2 configuration to default it works again. So i suppose there was something wrong with a message that was passed to rviz2 that it could not interpret.

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
