### ISSUE TITLE
How to write a custom plugin based on ros2_humble

### ISSUE THREAD

**Issue by HeiNobody** [ros2/rviz#1190]
rviz2 does not have the function of combining plugins. Based on ros2_humble, we use "colcon build" to compile. I want to write a custom plugin that can display three pictures and an integer in msg. Can anyone give me an example? Thank you very much.

**Comment by ahcorde** [comment]
If you want to write your own display please check [this tutorial](https://docs.ros.org/en/rolling/Tutorials/Intermediate/RViz/RViz-Custom-Display/RViz-Custom-Display.html).

In the future, please use one of the supported channels for help requests like this, such as the [Robotics Stack Exchange](https://robotics.stackexchange.com/). GitHub tickets should be used for bugs and enhancement tracking, not technical assistance.
