### ISSUE TITLE
Regarding the issue of being unable to load external files *. dae

### ISSUE THREAD

**Issue by SemanticCollaboration** [ros2/rviz#1213]
I recently downloaded a world description file in SDF format from the Gazebo website. When I tried to display the car model in rviz 2, I encountered the following difficulties. Thank you very much for helping me analyze the cause and find a solution.
![截图 2024-06-03 16-46-03](https://github.com/ros2/r
![截图 2024-06-03 16-45-19](https://github.com/ros2/rviz/assets/154821510/75f9ca90-80df-4026-95ae-bb4bb6f75d5b)
![截图 2024-06-03 16-44-18](https://github.com/ros2/rviz/assets/154821510/ca1c9699-c5d4-42e3-8598-6ee9139fbdc5)
viz/assets/154821510/d6e6bd12-3c9f-4083-9f2e-a6e4ad670175)
![截图 2024-06-03 16-45-42](https://github.com/ros2/rviz/assets/154821510/7fd235b7-fd53-4269-8403-1cdc8361df8e)
![Uploading 截图 2024-06-03 16-45-19.png…]()

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
