### ISSUE TITLE
`Tool::processKeyEvent` return value seems ignored

### ISSUE THREAD

**Issue by roncapat** [ros2/rviz#1256]
`int SelectionTool::processKeyEvent` return value is discarded in every call is made to it.

Quick search: https://github.com/search?q=repo%3Aros2%2Frviz%20processKeyEvent&type=code

See, in some tools `Render` is returned but ignored. It doesn't seem to be an issue, however if we try to return something else (for example, `Finished`) the transition won't happen / the tool will not be disabled.

Example of `Render` being returned in current codebase:
https://github.com/ros2/rviz/blob/a72ef90031c25fceb0b9e58ce3fef58fc246584f/rviz_default_plugins/src/rviz_default_plugins/tools/select/selection_tool.cpp#L180-L190

I propose to handle the return value as it is done here for mouse event handler:
https://github.com/ros2/rviz/blob/a72ef90031c25fceb0b9e58ce3fef58fc246584f/rviz_common/src/rviz_common/visualization_manager.cpp#L623-L637

CC: @giafranchini

**Comment by MichaelOrlov** [comment]
@ahcorde Could you please help to triage this issue?

**Comment by roncapat** [comment]
Just for additional context, see #1257. It implements support for "Finished" flag in a back-portable way, while support for "Render" flag may be more complex to be introduced without breaking API.

**Comment by roncapat** [comment]
I would keep this one open until the second PR to handle "Render" flag gets merged (I'll open it in a few days, sorry).

**Comment by ahcorde** [comment]
Thank you for the patch @roncapat. Closing this issue

**Comment by roncapat** [comment]
You're welcome :)
