### ISSUE TITLE
Problem on Rviz2 map warning

### ISSUE THREAD

**Issue by edo11-tech** [ros2/rviz#1290]
This is my error info: 

[INFO] [launch]: All log files can be found below /home/edoardo/.ros/log/2024-11-05-16-55-24-350495-Edo-64923
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [async_slam_toolbox_node-1]: process started with pid [64946]
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/slam_toolbox'
[async_slam_toolbox_node-1] [INFO] [1730822124.630566847] [slam_toolbox]: Node using stack size 40000000

![Screenshot 2024-11-05 165714](https://github.com/user-attachments/assets/ac97d5aa-4f77-4202-80e5-90e6e93d2bdf)

how can I solve It?

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
