### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [ros2/rviz#1299]
File:
rviz_default_plugins/test/rviz_default_plugins/pointcloud_messages.cpp line 224
Code:
std::vector<geometry_msgs::msg::Point32> points32; // <-- unused
  for (auto const & point : points) {
    geometry_msgs::msg::Point32 p;
    p.x = point.x;
    p.y = point.y;
    p.z = point.z;
    message.points.push_back(p);
  }
  return std::make_shared<sensor_msgs::msg::PointCloud>(message);
}

**Comment by ahcorde** [comment]
@maddin200 do you mind to open a PR ?

**Comment by ahcorde** [comment]
https://github.com/ros2/rviz/pull/1301
