### ISSUE TITLE
Issues in the RViz release candidate

### ISSUE THREAD

**Issue by greimela-si** [ros2/rviz#132]
## Setup
When running rviz from the nightly binary package
- [x]  ~~the library `libassimpd.4.so` can't be found.
It works after adding `opt/rviz_assimp_vendor/lib` to the `LD_LIBRARY_PATH`~~
- [x] ~~the symbol `_ZTIN4YAML13BadConversionE` can't be found.
It works after adding `opt/rviz_yaml_cpp_vendor/lib` to the `LD_LIBRARY_PATH`~~

I can't reproduce these issues anymore.

## GUI

**Menu**
- The link to rviz wiki redirects to the ros1 rviz wiki (see #145)

### Panels
**Displays panel**
- [x] An existing error message is not removed when the error is resolved
    - e.g. the message that tf is not able to transform between two frames does not disappear after this transformation is provided
- [x] The error message field can be edited

**View controller panel**
- [x] The orbit view controller has stereo enabled per default. This results in the image being slightly shifted
- [x] Clicking on a saved state does not load it
- [x] New states can be saved, but not renamed or removed

### Displays

**PointCloud**
- [x] Decay time > 0 results in flickering points

**Grid**
- [x] After adding an extra Grid display, it cannot be removed

## Console output
- [x] The default scene is still loaded in the background
```
[ERROR] [rviz2]: WARNING: rviz_sphere.mesh is an older format ([MeshSerializer_v1.8]); you should upgrade it as soon as possible using the OgreMeshUpgrade tool
```
- [x] Missing material `BaseWhiteNoLighting`
```
[ERROR] [rviz2]: Can't assign material BaseWhiteNoLighting to SubEntity of Shape1 because this Material does not exist in group rviz_rendering. Have you forgotten to define it in a .material script?
```

**Comment by wjwwood** [comment]
Since #138 has been merged, I'll close this. @greimela-si can you open issues for any of the remaining issues here?

Thanks again for testing and fixing things up guys!

**Comment by greimela-si** [comment]
I'd say the one with the error message is a won't fix, since the message is immediately overwritten most of the time.
I created #145 for the wiki link issue.
