### ISSUE TITLE
fails to transform to the same frame as the fixed frame when there is no tf data

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#141]
Any of the displays we have so far will complain that they "cannot transform from 'X' frame to 'X' frame", where `X` is something like `map`. If there is tf data which mentions the frame it works, however. Some displays work despite complaining, e.g. Grid, but others do not work in my experience, e.g. PointCloud.

This might be related to the work arounds to avoid the message filters which haven't been fully ported yet.

**Comment by greimela-si** [comment]
I don't think this is related to the message filter workaround.
The Grid and PointCloud display just react differently to a tf2::LookupException.
The former just uses (0,0,0) as a fallback position, the latter does not accept new messages and therefore does not display anything.

I think this problem should be fixed upstream in tf2.
For example, `lookupTransform` could return the identity transformation when source and target frame are equal.

Alternatively we can check for this condition in the FrameManager, but I would prefer the upstream fix.

**Comment by wjwwood** [comment]
@greimela-si I agree with your assessment. We'll have to look at that next week.

**Comment by Martin-Idel-SI** [comment]
Since #298, we have a fix for this bug in RViz (TODO comments in the code to remove the fix when an upstream fix is availabe). Should we close this issue?
