### ISSUE TITLE
Displays don't always show data unless rviz is started first (with Fast-RTPS)

### ISSUE THREAD

**Issue by clalancette** [ros2/rviz#151]
I'm trying to visualize the demo here: https://github.com/ros2/ros2/wiki/dummy-robot-demo .  I'm on Linux/AMD64, using the Ardent debs and using Fast-RTPS.  If I start up the `dummy_robot_demo` first, then startup rviz2, I never seem to get the visualization properly.  If I start up rviz2 first, then `dummy_robot_demo`, things seem to work and I can see the visualization.  Switching to Opensplice also seems to make it work.

**Comment by dhood** [comment]
For me (on OS X from archives) this was just generally flaky with fastrtps, the order didn't matter. When I had data, it would cut out after a while. I suspect general throughput issues. Opensplice was reliable.

**Comment by gaoethan** [comment]
@clalancette it seems that the rviz2 finally works for you, can I check how you prepare the rviz2 to run normally ?

1. Binary or build from rviz2 source code ?
2. The way to start rviz2 with "ros2 run" isn't available, so what's your procedure to start rviz2 ? 

thanks.

**Comment by clalancette** [comment]
In this case, I was running from a binary.  I just ran the executable directly, i.e. `/opt/ros/ardent/bin/rviz2`

**Comment by clalancette** [comment]
This isn't a problem for me anymore, so I'm going to close this one out.
