### ISSUE TITLE
[rviz_rendering] The build currently fails under Windows

### ISSUE THREAD

**Issue by greimela** [ros2/rviz#18]
When building the current HEAD using ament build, I get the following error:
```
CUSTOMBUILD : CMake error : The following variables are used in this project, but they are set to NOTFOUND. [C:\ros2\ros2_ws\build\rviz_ogre_vendor\ogre-1.10.7.vcxproj]
         Please set them or make sure they are set and tested correctly in the CMake files:
         FREETYPE_FT2BUILD_INCLUDE_DIR (ADVANCED)
```

Shouldn't the build provide dependencies like freetype out-of-the-box?

**Comment by greimela** [comment]
I noticed that ogre searches for its dependencies in `rviz_ogre_vendor/ogredeps`, but that folder does not exist.

**Comment by wjwwood** [comment]
@greimela it can build freetype. I don't know why I am not seeing this issue. It might be possible that something else on my machine installed freetype somewhere. I don't know if it can be installed from choco or not.

You could try adjusting the settings in https://github.com/ros2/rviz/blob/ros2/rviz_ogre_vendor/CMakeLists.txt to either try to get it to build freetype for you or to have it look in the correct place if that is an issue.

**Comment by greimela** [comment]
I managed to adjust the `rviz_ogre_vendorConfig.cmake` so that it finds freetype and zlib correctly.
PR is being prepared.
