### ISSUE TITLE
RViz segfault on macOS (v. 10.13.2) with latest master

### ISSUE THREAD

**Issue by botteroa-si** [ros2/rviz#180]
Following the change from static to dynamic linking, on Apple (on Linux and Windows this problem doesn't occur) RViz crashes at startup with a segfault. 
The problem was traced back to the `params["externalWindowHandle"] = Ogre::StringConverter::toString(window_id);` line, in render_system.cpp (line 428). When it is commented out, the segfault doesn't happen, but, of course, RViz starts with the render window detached from the application window. 

Proposed Solution: apparently, updating to the latest version of Ogre fixes the problem.

**Comment by Martin-Idel-SI** [comment]
Upon closer inspection, the error still persists with Ogre 1.10.11. However, it sometimes works, so maybe there is a race condition somewhere. We'll investigate.

**Comment by botteroa-si** [comment]
After simply deleting the install and build folders and building everything again, RViz works fine again, and no segfault occurs. It is not clear what the reason behind this behaviour is.

**Comment by wjwwood** [comment]
@botteroa-si, I believe @Martin-Idel-SI said it was possibly a race condition, so maybe you just got lucky after rebuilding? Can you confirm that it never happens anymore?

**Comment by botteroa-si** [comment]
@wjwwood, before rebuilding the segfault would happen 95% of the times I tried to launch RViz. After rebuilding yesterday afternoon, it hasn't happened again yet, and I have launched and used RViz quite some times since then. I'll try to rebuild again some other times to have some statistics.

**Comment by botteroa-si** [comment]
@wjwwood, I have now deleted the install and build folders and rebuilt three more times, and all three times I have experienced no segfault.

**Comment by wjwwood** [comment]
Cool, thanks for following up. In that case, I'll close this until someone else runs into it.
