### ISSUE TITLE
pointcloud display in rviz2 for ros 2

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rviz#185]
I have created a demo node which publishes the point cloud data from .pcd file in a senosr_msgs/PointCloud2 format.The rviz tool for ros 2 is able to detect the pointcloud topic name, but it is coming under unvisualizable topic.

Is there any way where I can visualize the sensor_msgs/PointCloud data in rviz display for ROS2 environment ?

**Comment by greimela-si** [comment]
This issue should be fixed on the current master.
Are you using the release version or are you building from source?

As a workaround you can add a PointCloud display by name and then fill in the topic name on the left side.

![rviz topic name](https://user-images.githubusercontent.com/31658255/35557465-829d6432-05a5-11e8-8d7c-c85bc78db937.png)

**Comment by sagniknitr** [comment]
@greimela-si I am using the ardent branch of the rviz for ros 2.Is the issue fixed in the rviz 2.0.0 release ?

**Comment by sagniknitr** [comment]
![pointcloud](https://user-images.githubusercontent.com/17951883/35568005-2dfa9fb0-05ed-11e8-8d73-a350e6064bd9.png)


I have attached my rviz window.As you can see, the pointcloud2 display window is receiving the messages. but no display is coming in the viewing area.

**Comment by jeising** [comment]
You would need to publish a transform e.g.:
`ros2 run tf2_ros static_transform_publisher -- 0 0 0 0 0 0 map pointcloud_frame`

**Comment by sagniknitr** [comment]
@jeising Is the `pointcloud_frame` you mentioned in the command above is same as the` header.frame_id `of the PCL message ?

**Comment by sagniknitr** [comment]
![point_cloud_issu2](https://user-images.githubusercontent.com/17951883/35574236-4160fa74-05ff-11e8-95c4-fd254c4d43d9.png)

@jeising Did what you mentioned.Still no output.

**Comment by Martin-Idel-SI** [comment]
Two more questions:
- Can you switch the Style from "Flat Squares" to "Points"? Maybe there is a rendering problem and points is the easiest. 
- Did you ever try to publish PointCloud instead of PointCloud2 and if yes, did you see anything?

**Comment by greimela-si** [comment]
We were able reproduce the bug, here is the bugfix PR: #189

**Comment by sagniknitr** [comment]
@greimela-si Thanks for the PR:#189. It solves my problem.
