### ISSUE TITLE
[rviz_rendering] resizing does not appear to affect the rendering window

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#2]
After resizing you don't get messages that the resizing function is getting called and you don't see it resize, instead you get:

![capture](https://user-images.githubusercontent.com/100427/29808943-fb9cc6be-8c4e-11e7-9c26-ee65f62d0154.PNG)

**Comment by greimela** [comment]
This can be fixed by removing `tabs->setFixedSize(245, 245)` in `rendering_example.cpp`.
