### ISSUE TITLE
Segfault when closing rviz with camera_displays and multiple image_displays

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rviz#201]
The following steps lead to a segfault when cleaning up the DisplayGroupVisibility property when closing rviz (both Windows and Linux):
-- Add Camera Display
-- Add Image Display (more than thrice)
-- Close the application (don't save or do save the config).
This is a weird issue, but we could only recreate it on closing. On Windows, it's a bit annoying as you get the "RViz stopped working" window.

The full error is:
```
Thread 1 "rviz2" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a83d9e in rviz_common::properties::Property::getParent (this=0xe80f0f0100000005) at /home/martin/gitRepos/rvizPort/aos-rviz2/src/rviz/rviz_common/src/rviz_common/properties/property.cpp:242
242	  return parent_;
```
The call stack shows that this happens in the destructor of VisualizerApp, when removing an image display from the DisplayGroupVisibility property

**Comment by clalancette** [comment]
As far I can tell, this doesn't happen anymore.  I'm going to close this out, but feel free to reopen if this is still occurring for you.
