### ISSUE TITLE
Timeout to download Ogre is too short

### ISSUE THREAD

**Issue by russkel** [ros2/rviz#230]
I am trying to build rviz_ogre_vendor and it has to download a 120MB zip file. The max I can get from github release site seems to be about 200kb/s which gives an ETA of about 7 minutes. I think this timeout should be removed or increased quite a lot.

https://github.com/ros2/rviz/blob/ros2/rviz_ogre_vendor/CMakeLists.txt#L127

**Comment by wjwwood** [comment]
That's fine with me, can you open a pull request to do that?

**Comment by russkel** [comment]
Sure can. My cmake domain knowledge is non-existent so I will read up on the TIMEOUT argument before I make a PR.

**Comment by wjwwood** [comment]
@russkel sure, if you need help let me know.
