### ISSUE TITLE
[rviz_rendering] System assimp exporting wrong library dir

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rviz#248]
I'm using ubuntu bionic that has assimp 4.1.0. As a result `rviz_assimp_vendor` doesnt build the assimp from source.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
library_abs
    linked by target "rviz_rendering" in directory /root/ros2/ros2_ws/src/ros2/rviz/rviz_rendering
```

I narrowed it down to assimp exporting the wrong library dirs:
`ASSIMP_LIBRARY_DIRS:/usr/lib/lib/x86_64-linux-gnu`

It seems to not be handling the architecture specific dir properly and duplicate the "lib" in the provided path. So I guess we would need to convince either assimp devs or debian assimp maintainers to use GNUInstallDirs

/cc @wjwwood as maintainer
/cc @nuclearsandwich as the person wit hthe most experience with GNUInstallDirs

Edit: Actually they are using GNUInstallDirs. Didn't look further into it, likely just a tweak to the generated Config file.
What worked for me (though I'm not sure that's the "right" solution: https://github.com/mikaelarguedas/assimp/commit/a44071380c093856242e3d7d1e520bbf2903779c

Before the hack: 
```
-- ASSIMP_LIBRARY_DIRS:/usr/lib/lib/x86_64-linux-gnu
-- ASSIMP_ROOT_DIR:/usr/lib
-- ASSIMP_INCLUDE_DIRS:/usr/lib/include
```

After the hack:
```
-- ASSIMP_LIBRARY_DIRS:/usr/lib/x86_64-linux-gnu
-- ASSIMP_ROOT_DIR:/usr
-- ASSIMP_INCLUDE_DIRS:/usr/include
```

**Comment by nuclearsandwich** [comment]
They've included GNUInstallDirs but they are not actually using any of the defined variables in their install targets (that I can tell). Maybe including gnuinstalldirs provides other side effects that I am not familiar with.

The Debian package appears to be specifying the multiarch dir "by hand" in a configuration step. https://anonscm.debian.org/git/collab-maint/assimp.git/tree/debian/rules#n40

While the CMake configuration assumes that the directory three up from the cmake config file is the root directory / install prefix. Assimp's config has independently specifiable / overrideable library. I'm working on a pull request I can open alongside an upstream issue to set the ASSIMP_ROOT_DIR variable based on the installation prefix.

**Comment by mikaelarguedas** [comment]
awesome, thanks @nuclearsandwich !

**Comment by nuclearsandwich** [comment]
I've opened an issue upstream, assimp/assimp#1914, and proposed a solution assimp/assimp#1915 that will work for us. I'm not sure if there's a workaround in the meantime without overriding ASSIMP_* variables by hand in our vendor CMake. Which we could do if they match the expected broken paths.

**Comment by mikaelarguedas** [comment]
As discussed offline, we should also ping the Debian maintainer to report the issue of the current deb hoping that it gets patched before this fix makes it upstream and in a packages release

**Comment by nuclearsandwich** [comment]
Debian bug (baby's first!) link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896835

**Comment by ArkadiuszNiemiec** [comment]
Could you tell me how to workaround this problem? I have tried to build and install `assimp:master` but it did not help.

**Comment by clalancette** [comment]
The original fix from Mikael was merged long ago, and current versions of assimp (5.2) don't seem to have this bug anymore.  So I'm going to close this as fixed, but feel free to reopen if you think this is still a problem.
