### ISSUE TITLE
where is the class rviz_common::Panel?

### ISSUE THREAD

**Issue by ChangsongYu** [ros2/rviz#260]
Hi guys,

I am responsible for migration of rviz from ros1 to ros2. However, I found that the class rviz_common::Panel is not yet available in ros2. Is there any substitute for rviz_common::Panel of ros1? Thanks in advance!

**Comment by ChangsongYu** [comment]
sorry, I mean rviz::Panel.

**Comment by wjwwood** [comment]
I think the root issue was that the `rviz/rviz_common::Panel` is not a public interface in ROS 2 at the moment. I think that can be fixed with a simple pr. I'll reopen for now.
