### ISSUE TITLE
Flaky rviz_common.selection_manager_test

### ISSUE THREAD

**Issue by mjcarroll** [ros2/rviz#271]
On the `nightly_osx_repeated` job, we've had a new test start failing since job 1106:

https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/1106/testReport/junit/(root)/rviz_common/selection_manager_test_gtest_missing_result/

It would appear that the test is killed before it finishes.

**Comment by botteroa-si** [comment]
We also managed to reproduce this behaviour on Mac. It is caused by a `BAD_ACCESS` exception thrown during the tear down (in particular, in the destructor of `SelectionManager`).
We are investigating the issue.
