### ISSUE TITLE
Rviz2 installation using ament build fails

### ISSUE THREAD

**Issue by sagniknitr** [ros2/rviz#276]
Building the master branch for rviz2 using ament build is failing.

Following is the error : 

`
In file included from /home/sagnik/rviz_master/src/rviz/rviz_default_plugins/src/rviz_default_plugins/displays/grid/grid_display.cpp:250:0:
/home/sagnik/Work/ROS/ros2_ardent_alvacore/install/include/pluginlib/class_list_macros.hpp:49:59: error: extra ‘;’ [-Werror=pedantic]
   CLASS_LOADER_REGISTER_CLASS(class_type, base_class_type);
`                                                           ^

I am using the the latest release of ros2 (Ardent Apalone).

**Comment by anhosi** [comment]
The current master of rviz2 will only build against a current master of ros2. The latest release is not enough.
