### ISSUE TITLE
[rviz_common] Pluginlib adoption

### ISSUE THREAD

**Issue by jeising** [ros2/rviz#29]
There is the plugin mechanism for ros1, which needs to be adopted for ros2 rviz.

**Comment by wjwwood** [comment]
@jeising there is this branch we started a long time ago:

https://github.com/ros/pluginlib/commits/ros2

It's probably the best starting place for porting pluginlib to ros2. Thanks to @mikaelarguedas for reminding me of it.

**Comment by wjwwood** [comment]
This has been done now, and is being used since #123.
