### ISSUE TITLE
Crash when using OpenSplice and selecting a wrong topic

### ISSUE THREAD

**Issue by greimela-si** [ros2/rviz#291]
When using OpenSplice as DDS implementation RViz crashes as soon as one selects a topic containing an invalid message type.
E.g. it crashes when selecting the `/clock` topic in the Marker Display.

The issue seems to be located in OpenSplice itself (according to the log output).
However, we should probably catch this error in RViz.

**Comment by ahcorde** [comment]
the https://github.com/ros2/rmw_opensplice repository was archived, this issue is outdated
