### ISSUE TITLE
Not all tools have hotkeys to reach them

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rviz#304]
Since the help has now been ported, it becomes apparent that some tools have hotkeys to activate (and/or deactivate) them, while others don't. I don't see a good reason why this should be the case.

Here is a suggestion for hotkeys for already ported tools that don't have one so far. What do you think @wjwwood ?

Focus Camera: C   (F is taken by some commands)
Publish Point Tool: U (P is taken)
Measure Tool: N  (M is taken, close by...)

**Comment by wjwwood** [comment]
That sounds fine to me, but it would be great (if the diff is simple enough) to backport to rviz in ROS 1 so that we don't accidentally get divergent on the hotkeys.
