### ISSUE TITLE
Render panel disappears on File -> Save Image

### ISSUE THREAD

**Issue by greimela-si** [ros2/rviz#351]
When clicking `File` -> `Save Image`, a new window opens to save an image of the current scene.
However, this action clears the render panel in the main window.

![rviz_save_image_error](https://user-images.githubusercontent.com/31658255/45154760-f36f2580-b1d8-11e8-8e08-ffda9edf4d76.png)

Closing the new window does not restore the render panel, it stays blank.
Klicking the `Retry` button in the new window does restore the render panel.

**Comment by gbalke** [comment]
It seems like this bug has resolved itself :thinking: 

https://user-images.githubusercontent.com/11024792/133676803-df3ecc1a-6cbd-4e72-8eb0-096cde511288.mp4

**Comment by ahcorde** [comment]
I tried to reproduce this on rolling and galactic and I couldn't replicate it.

@greimela-si feel free to reopen the issue and add more information if the issue persist.
