### ISSUE TITLE
RViz configs for visual tests are not installed

### ISSUE THREAD

**Issue by AlessandroBottero** [ros2/rviz#372]
### Current Situation
At the moment the visual tests need two specific RViz configuration to run:
- `visual_tests_default_config.rviz`
-  `visual_tests_test_image_config.rviz`

These configs files, though, are not installed and, therefore, they can be found only in `src/rviz_visual_testing_framework/`, which is where the `VisualTestFixture` looks for them (see `rviz_visual_testing_framework/src/visual_test_fixture.cpp` lines 55-60).

### Problem
This is an issue if the source files are not available (e.g. if someone who has installed ROS from binaries wants to run visual tests for a custom display that they are developing). In this case, in fact, the test configs won't be found and the default RViz config will be loaded instead, resulting in the failure of the visual tests.

### Possible Solution
The most straightforward solution to this problem would be to install the two config files and update accordingly the path used by the `VisualTestFixture` to find and load them.

**Comment by audrow** [comment]
@ahcorde This is good to close, right?
