### ISSUE TITLE
Failing tests on ARMHF

### ISSUE THREAD

**Issue by zmichaels11** [ros2/rviz#445]
[ARMHF debug nightly build 184](https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_debug/184/testReport/) and [ARMHF release nightly build 188](https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_release/188/testReport/) reports 2 RViz tests failing for the last 138 builds.

Can we skip these tests?

**Comment by clalancette** [comment]
I'd rather see if it is possible to fix them.  Has anyone looked into the causes?  @emersonknapp ?

**Comment by zmichaels11** [comment]
The two tests that were failing are no longer listed as failing. 
I'm closing the issue.
