### ISSUE TITLE
Error with opensplice

### ISSUE THREAD

**Issue by hyunseok-yang** [ros2/rviz#450]
Hi all,

I tried to run all ROS packages through Opensplice DDS. 

But I got these error messages when the navigation 2 has been launched.

> [lifecycle_manager-1] [INFO] [lifecycle_manager] Configuring and activating amcl
> [amcl-3] [INFO] [amcl] Configuring
> [amcl-3] [INFO] [amcl] initTransforms
> [amcl-3] [WARN] [rcl.logging_rosout] Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
> [amcl-3] [INFO] [amcl] initPubSub
> [amcl-3] [INFO] [amcl] Subscribed to map topic.
> [amcl-3] [INFO] [amcl] Activating
> [lifecycle_manager-1] [INFO] [lifecycle_manager] Configuring and activating world_model
> [world_model-4] [INFO] [world_model] Configuring
> [world_model-4] [INFO] [global_costmap.global_costmap] Configuring
> [world_model-4] [INFO] [global_costmap.global_costmap] Using plugin "static_layer"
> [world_model-4] [INFO] [global_costmap.global_costmap] Using plugin "inflation_layer"
**> [world_model-4] [WARN] [] Error occurred while doing error handling.
> [world_model-4] [FATAL] [world_model] Lifecycle node entered error state
> [lifecycle_manager-1] [ERROR] [lifecycle_manager] Failed to change state for node: world_model
> [lifecycle_manager-1] [ERROR] [lifecycle_manager] Failed to bring up node: world_model, aborting bringup**
> [world_model-4] [INFO] [global_costmap.global_costmap] StaticLayer: Resizing costmap to 712 X 1211 at 0.100000 m/pix
> 

Anyone have an idea why this happened?

**Comment by jacobperron** [comment]
I'm not sure this is the appropriate place to for this issue. It doesn't appear related to RViz at all. Perhaps https://github.com/ros-planning/navigation2 is a better place to open an issue?

Edit: Also make sure to include as many details as you can, e.g. what version of ROS, installation type, the commands you ran that lead to the error.
