### ISSUE TITLE
Rviz2 marker lifetime

### ISSUE THREAD

**Issue by ZhilaiShen** [ros2/rviz#464]
I am wondering if the "lifetime" of markers can be applied. When I try to delete the CUBE marker by using marker.lifetime = rclcpp::Duration(1), the marker is not deleted automatically from rviz. Is there something else I should try?

**Comment by Martin-Idel** [comment]
The code for deletion is present, so in principle markers with expired lifetime should get deleted automatically. I had a quick look and found two fishy areas in the code, maybe you can test whether this already solves the problem? If not, I'll have to come back and investigate this further.

**Comment by ZhilaiShen** [comment]
Hi Martin, sorry for the late update, but the problem is solved. I used marker.lifetime=rclcpp::Duration(100*time), where time is a static constexpr int and has value of 100000000. I thought it might relate to the time I use. I am not sure if it is a problem if I send the messages inside a Docker container and plot it using RVIZ2 under UBUNTU 16.04, but everything is working right now. Feel free to close this issue.

**Comment by jpapon** [comment]
Anyone that comes across this in the future, remember that rclcpp::Duration constructor is in nanoseconds, and if you use small integers, or worse, floats, expecting that is in seconds, you'll get weird behavior.
If you specify the value in nanoseconds, the lifetime will work correctly.
See:
https://docs.ros2.org/ardent/api/rclcpp/classrclcpp_1_1_duration.html
