### ISSUE TITLE
Window Empty after Screenshot

### ISSUE THREAD

**Issue by allenh1** [ros2/rviz#480]
Rather odd, but if you do a File -> Save Image, the viewing of the rendered model seems to disappear.

![image](https://user-images.githubusercontent.com/2013091/69268991-1bf4fc80-0b9e-11ea-9699-31dfb04d1bda.png)

The FPS is indicative of work being done, but there's an inability to see anything.

I should also point out I'm on Windows 10. Not sure if this affects Ubuntu or OS X.

**Comment by allenh1** [comment]
In the source, it appears things propagate from Ogre.

https://github.com/ros2/rviz/blob/1866827f2277ff79e7c4ff99d1612d6648ecdc6e/rviz_rendering/src/rviz_rendering/ogre_render_window_impl.cpp#L97-L101

**Comment by Martin-Idel** [comment]
This seems like a duplicate of #351

**Comment by allenh1** [comment]
@Martin-Idel yep. My mistake.
