### ISSUE TITLE
[rviz_rendering] there is an extra window opened on Windows

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#5]
When running the `rendering_example` demo on Windows you get an extra window that exists outside of the Qt window. I think this is the "dummy" window which is used to query the capabilities of the graphics card and ogre. Perhaps it just needs to be cleaned up properly on Windows. You can just close it and it does not affect the program (or it seems to not).

![capture](https://user-images.githubusercontent.com/100427/29815691-6d5eb106-8c66-11e7-87c7-19f7edfa7cba.PNG)

**Comment by greimela** [comment]
It is possible to hide the window using `Ogre::RenderWindow::setHidden(true)`.
This results in the window disappearing immediately after showing.

According to the [ogre forum](http://www.ogre3d.org/forums/viewtopic.php?f=3&t=62985), it should also be possible to pass a parameter `hidden=true` to hide the window from the start. 
However, this did not work for me.
