### ISSUE TITLE
Frame Transformer Message Filter Display has it's queue-size hardcoded to 10

### ISSUE THREAD

**Issue by dkuenster** [ros2/rviz#502]
https://github.com/ros2/rviz/blob/fcc4b1b20d366203295fd4e6c245c4d79615a0e7/rviz_common/include/rviz_common/message_filter_display.hpp#L126

Having this parameter hardcoded to 10 caused nearly all messages in the odom frame to be dropped, when I was using the teb-planner with the nav2 stack.The teb planner sends a lot of messages in the odom frame for debugging purposes.
The error message in this case just says dropped for reason unknown, which made debugging difficult.
This should probably be a parameter and a more descriptive error message would help.

**Comment by jacobperron** [comment]
+1

@dkuenster If you have time to propose a fix in the form of a pull request, I'm happy to review it!
