### ISSUE TITLE
Deprecated Qt functions (Qt 5.14.1) in rviz_common

### ISSUE THREAD

**Issue by brawner** [ros2/rviz#508]
When using the most recent patch version of Qt (5.14.1), there are build warnings about deprecated functions in rviz_common.

```
panel_dock_widget.cpp:50, MSBuild, Priority: Normal
--
'QPalette::Background': Use QPalette::Window instead


property.cpp:254, MSBuild, Priority: Normal
--
'Qt::TextColorRole': was declared deprecated
```
The recommended replacement for `Qt::TextColorRole` is `Qt::ForegroundRole`.

https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum
https://doc.qt.io/qt-5/qt.html#ItemDataRole-enum

https://ci.ros2.org/job/ci_windows-container/123/warnings43Result/

**Comment by claireyywang** [comment]
closing since PR is merged
