### ISSUE TITLE
[rviz_common] cleanup usage of tf2 buffer versus transform listener

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#52]
Previously rviz passed the `tf::TransformListener` around as an API entry point for tf, but in `tf2` these functions have been moved to the `tf2_ros::Buffer` class, and there is still a transform listener, but it doesn't have any useful public API, so it probably doesn't need to be passed around.

Right now these are created here:

-
 https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.cpp#L342-L344

But places like this need to be cleaned up:

- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/frame_manager.cpp#L59-L67

Also, we should manage the node better here:

- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/visualization_frame.cpp#L343

Currently I believe tf will create it's own node :nauseated_face:. We should also consider how to abstract this to minimize changes needed to support ROS 1 (though we can continue and should continue to tf2 in ROS 1).

**Comment by Martin-Idel-SI** [comment]
This is our understanding here:

- The transform_listener creates its own node unless you hand it a node handle, which can be done (see https://github.com/ros2/geometry2/blob/ros2/tf2_ros/src/transform_listener.cpp#L53 ).
- The transform_listener connects to ROS and subscribes to the transform data, i.e. we need to start a transform listener and hold it somewhere, but we don't need to pass it around.
- Looking at the API of the buffer, there are two differences between ROS and ROS2: 
a) ros::time is changed to tf2::TimePoint (as is Duration). In principle, we'd need an adapter of the time/duration classes and for tf2, if we want to use the same code for both, but I'm wondering whether tf2::TimePoint is supposed to provide this abstraction in the near future?
b) message types are in different packages and might be of different format.
--> Note: The message types are only return types. Therefore, if tf2 would bring its own time adapter for ROS and ROS2 time (or use a common time adapter, if this exists), then we should get away with the same code for ROS and ROS2 using tf2.

Summarizing, I would see the following todos:
- Cleanup setup of transform_listener passing the rviz node.
- Don't pass the transform_listener around.
- Investigate time abstraction in tf2 or write our own if feasible (future).

**Comment by Martin-Idel-SI** [comment]
This was overhauled in #346, I think this could be closed now
