### ISSUE TITLE
[rviz_common] re-enable SyncApprox in the frame manager

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#54]
See:

- https://github.com/ros2/rviz/blob/ca8f42e43ba9eaa6e15434b47906d7580da1c14a/rviz_common/src/rviz_common/frame_manager.cpp#L189-L206

I believe this function has moved into `tf2_ros::Buffer` somewhere, but @tfoote suggested that there might be a better way to do this now. @tfoote if you have a minute could repeat the suggestion here? I seem to have lost track of it...

**Comment by tfoote** [comment]
We've simplified the API and getLatestCommonTime is now internal, though it's exposed for backwards compatibilty if really necessary. [`_getLatestCommonTime`](https://github.com/ros/geometry2/blob/indigo-devel/tf2/include/tf2/buffer_core.h#L285)

I'd recommend calling lookupTransform with Time(0) and then read the timestamp of the resultant data which should be reset to the latest time if the lookupTransform succeeded.
