### ISSUE TITLE
RViz use custom shader for Mesh_Resource marker

### ISSUE THREAD

**Issue by Tingcccc** [ros2/rviz#559]
Hello,
Could I use custom shader for mesh resource marker? 
How do I add the shader code in Rviz then bind shader and mesh material?
Look forward to your reply. Thank you!

**Comment by sloretz** [comment]
@wjwwood friendly ping :)

**Comment by wjwwood** [comment]
Hi @Tingcccc, I do not believe this is currently possible unless you make a custom display plugin, which case you can use Ogre directly and therefore any shader you desire.
