### ISSUE TITLE
[foxy] Dropdown topic menu doesn't filter topics

### ISSUE THREAD

**Issue by doisyg** [ros2/rviz#566]
Hi,
Coming from ROS1 here. The topic menu in rviz2 is not filtering topics by type. For instance, when selecting a laserscan display, I can see all topics in its dropdown menu. In ROS1 I would have access only to laserscan type topics.
Is this a bug or a a desired behavior ?

**Comment by Martin-Idel** [comment]
Yes, this is well-known (see the README.md under "Not yet ported") - the feature couldn't be ported at the time because message traits didn't exist. Maybe it can be ported now, I may have a look later this month.
