### ISSUE TITLE
Absolute paths for dependencies in RViz shipped with ROS2 Foxy

### ISSUE THREAD

**Issue by joelloo** [ros2/rviz#601]
I have installed ROS2 Foxy on Windows 10 using the binaries and instructions at https://index.ros.org/doc/ros2/Installation/Foxy/Windows-Install-Binary. I am trying to develop plugins for RViz2 that take in my custom data types. When compiling my plugin source against the RViz2 libraries shipped with ROS2 Foxy, I receive the following error messages:
```
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
---
--- stderr: autovision_ocu
CMake Error in CMakeLists.txt:
  Imported target "rviz_common::rviz_common" includes non-existent path

    "C:/ci/ws/install/opt/rviz_assimp_vendor/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

For brevity, I only showed the error message for rviz_common above. However, there are absolute paths to the ```C:/ci/ws/install/opt``` directories specified for assimp headers and libraries in both rviz_common and rviz_rendering. Manually correcting the paths for headers in libraries in both ```rviz_commonExport.cmake``` and ```rviz_renderingExport.cmake``` to the ```ros2/opt``` directory (which contains assimp headers and libraries) finally allowed my code to compile.

It seems like there is some issue during the build of RViz binaries for Windows that specifies an absolute path, preventing it from being relocatable?

**Comment by binitshah** [comment]
Hi, I'm experiencing this bug as well. I've made a Rviz2 panel called [JoystickPanel](https://github.com/binitshah/JoystickPanel) that shows the same build error as above on Windows. It builds fine on MacOS and Ubuntu.

**Comment by binitshah** [comment]
@mjcarroll If I could help resolve this, perhaps with steps to reproduce the issue, let me know.

**Comment by clalancette** [comment]
We did a whole bunch of work for Humble to fix this particular issue, and as far as I can tell no longer exists in the latest binaries.  Given that, and that Foxy is now End-of-Life, I'm going to close this out.  Feel free to reopen if you are still seeing this issue.
