### ISSUE TITLE
Zoom with mouse wheel not working

### ISSUE THREAD

**Issue by hdino** [ros2/rviz#605]
In rviz2 version 8.2.0-1focal.20200911.234728 on Ubuntu I cannot zoom with the mouse wheel (default settings). Zooming with a right-click does work though.

I tried to track down this error, but when I compile rviz2, it links to my installation in `/opt/ros/foxy`.

Update: This problem still occurs in version 8.2.0-1focal.20200921.203534.

**Comment by Phymin** [comment]
I have also encounter this problem in ros2 foxy

**Comment by paulerikf** [comment]
Seems like the "Interact" mode is acting just like the "Move camera" mode again?

**Comment by hdino** [comment]
True, for me both have the same behaviour.

**Comment by jacobperron** [comment]
@paulerikf @hdino Can you confirm if the the interact vs move camera modes worked correctly in a previous ROS 2 version?

**Comment by paulerikf** [comment]
@jacobperron Just checked my Eloquent install, with either "Move Camera" or "Interact" active the mouse icon is the "Move Camera" icon, however mousewheel zoom is available in both. Weird.

What is the difference supposed to be?

**Comment by jacobperron** [comment]
@paulerikf Thanks for checking. I think the behavior you see is correct; if the "interact" tool is not hovering over an interactive element (e.g. an interactive marker), then it falls back to camera controls. The same is true in ROS 1 I'm pretty sure.

It sounds like zooming with the mousewheel has regressed in Foxy.
