### ISSUE TITLE
Render window disappears after saving an image

### ISSUE THREAD

**Issue by hdino** [ros2/rviz#606]
After saving an image in rviz2 version 8.2.0-1focal.20200911.234728 on Ubuntu, the render window disappears. So far I haven't find a way to bring it back, only a restart of the application helps. When I click, hold and move the mouse in the area where the render window was, messages like `in RenderPanel::mouseMoveEvent()` show up in the terminal.

Update: This problem still occurs in version 8.2.0-1focal.20200921.203534.

**Comment by mjeronimo** [comment]
@hdino I've just submitted a fix for this. Until that gets integrated, as a work-around, I've found that you can check and then uncheck "Save entire rviz window" in the image saving dialog box and it will restore the render window.
