### ISSUE TITLE
[rviz_rendering] Wrong movable text position with multiple lines

### ISSUE THREAD

**Issue by Dayelyn** [ros2/rviz#632]
***Environment***
Ubuntu 20.04.1 LTS, ROS2 foxy;
***Phenomenon***
When I am trying to display text with ```visualization_msgs::msg::Marker::TEXT_VIEW_FACING```, it turns out that the rotation center of the text with multiple lines is not exactly the same with where I set, while a single line text is placed at the correct position;
***Analysis***
Then I try to read the source code in ```rviz/rviz_rendering/src/rviz_rendering/objects/movable_text.cpp```, in [line 392](https://github.com/ros2/rviz/blob/3b355f876d5eb3029d1346e088033450c4152388/rviz_rendering/src/rviz_rendering/objects/movable_text.cpp#L392)  it shows

```
void
MovableText::calculateTotalDimensionsForPositioning(float & total_height, float & total_width) const
{
  Ogre::Real effective_char_height = char_height_ * effective_char_height_factor;

  total_height = effective_char_height;
  total_width = 0.0f;
  float current_width = 0.0f;
  for (auto & character : caption_) {
    if (character == '\n') {
      total_height += effective_char_height + line_spacing_;
      total_width = current_width > total_width ? current_width : total_width;
    } else if (character == ' ') {
      current_width += space_width_;
    } else {
      current_width += font_->getGlyphAspectRatio(character) * effective_char_height;
    }
  }
  total_width = current_width > total_width ? current_width : total_width;
}
```
that when a newline character is read, character width of previous line `current_width` is compared with `total_width`. `total_width` is considered as the horizontal alignment length, half of the length is the center of the multiple lines text, as shown in [line 422](https://github.com/ros2/rviz/blob/3b355f876d5eb3029d1346e088033450c4152388/rviz_rendering/src/rviz_rendering/objects/movable_text.cpp#L422)

```
float MovableText::getLineStartFromHorizontalAlignment(float total_width) const
{
  switch (horizontal_alignment_) {
    case H_LEFT:
      return 0.0f;
    case H_CENTER:
      return -0.5f * total_width;
    default:
      throw std::runtime_error("unexpected horizontal alignment");
  }
}
```

The purpose of the comparison is to find the longest line of all lines, but the truth is that `current_width` is keeping accumulated instead of setting to 0 when a newline starts. Then `total_width` will really be the "Total Width" of all text lines and the position will be wrong.

Apparently, a single line text will not have the problem.

**Comment by jacobperron** [comment]
@Dayelyn Thanks for the bug report and the detailed analysis. Would you care to propose a pull request fixing the issue?
