### ISSUE TITLE
Cannot View Images

### ISSUE THREAD

**Issue by bostoncleek** [ros2/rviz#646]
I am trying to view an image (sensor_msgs/msg/Image). The data is being published after echoing the topic. 

![rviznoimage](https://user-images.githubusercontent.com/36201047/107441636-c8e4cd80-6af2-11eb-913e-5282ce590360.png)

When running rviz I get the following message:
```
qt5ct: using qt5ct plugin
[INFO] [1612912407.586356395] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [1612912407.586447785] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
qt5ct: D-Bus global menu: no
```

**Comment by mjeronimo** [comment]
@bostoncleek Assuming that your topics match and the QoS settings also match, the next likely reason is that the sim_time settings don't match between the publisher and rviz. This is relevant as rviz uses a message_filter for its subscriptions and a sim_time mismatch won't allow the messages to pass.

**Comment by jacobperron** [comment]
Please also confirm that the frame ID in the camera message also matches the "Fixed Frame" in the RViz global options.

**Comment by bostoncleek** [comment]
@jacobperron I set the Fixed Frame to camera_color_optical_frame which is the frame ID on topic /camera/color/image_raw. The image is not available.

**Comment by mjeronimo** [comment]
@bostoncleek Did you confirm matching QoS and sim_time settings?

**Comment by clalancette** [comment]
No response in over 6 months, so closing.  Feel free to reopen if you are still having problems.
