### ISSUE TITLE
terminate called after throwing an instance of 'Ogre::ItemIdentityException'

### ISSUE THREAD

**Issue by jediofgever** [ros2/rviz#648]
Hi,
RVIZ2 seems to crash regularly due to an error I get. I searched the error in existing issues and found no similar report. It might be a bug or a programing mistake I am doing. In any case I believe its better to report. Here is what I get from debugger. 

![Screenshot from 2021-02-16 11-09-14](https://user-images.githubusercontent.com/18460336/108013968-d4327e80-7047-11eb-8302-bad163f47a94.png)

Sorry I cant copy text from xterm debug window hence the screenshot. But he error is in the tittle. 
What could be possible reason that triggers this ? 

ROS2 version is Foxy
The RVIZ installation is latest binary install of foxy. 

Thanks!

**Comment by clalancette** [comment]
There is some possibility that this was fixed in the `ros2` branch by #620 , so it may be worthwhile to try that out.
