### ISSUE TITLE
Low FPS in PointCloud2 visualization

### ISSUE THREAD

**Issue by k0suke-murakami** [ros2/rviz#662]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binary
- Version or commit hash:
  - Foxy
  - rviz2: 8.2.1-1focal.20210226.004041
- DDS implementation:
  - Fast-RTPS 
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce the issue

1. Clone my test repository
  a. `git clone git@github.com:k0suke-murakami/send_lots_of_points_node_ros2.git` 
2. Clone pcl_perception
  a. `git@github.com:ros-perception/perception_pcl.git`
  b. `git checkout foxy-devel`
3. Build 
4. Run
  a. `rviz2` @Terminal1
  b. `ros2 run send_lots_of_points_node_ros2 send_lots_of_points_node_ros2 1 200 1000` @Terminal2

#### Expected behavior
Tested in ROS1(melodic) with similar code (https://github.com/k0suke-murakami/send_lots_of_points_node_ros1)
`rosrun send_lots_of_points_node send_lots_of_points_node 1 200 1000`
FPS is not low for visualizing 200*1000 points in ROS1. It is around 21FPS.

https://user-images.githubusercontent.com/10920881/110898827-50686b00-8343-11eb-9b17-e864342b4173.mp4

#### Actual behavior

FPS is almost 0.

https://user-images.githubusercontent.com/10920881/110898799-3fb7f500-8343-11eb-864e-97af48bdae08.mp4

**Comment by adamdbrw** [comment]
We are investigating this at the moment and have some idea why this might be happening
