### ISSUE TITLE
Camera not showing LaserScan nor Odometry

### ISSUE THREAD

**Issue by martimorta** [ros2/rviz#667]
Hi,
minor issue here, trying to see a LaserScan on a Camera display, it shows the tf and robot model but it doesn't show a LaserScan, descriptive screenshot below on a Ubuntu 20.04 and Foxy. 
[edit] I noticed it doesn't show the Odometry arrows either.
Cheers
![rviz_not_showing_laser](https://user-images.githubusercontent.com/3284973/113559252-f0d74580-95f8-11eb-9ab1-d907f2dd9f91.png)

**Comment by mjeronimo** [comment]
@martimorta  I tried to reproduce on Foxy using the nav2 stack, but was unable to. Also tried the latest Rolling code. In both cases, I was able to view both the Odometry arrows and the laser scan. I'll need more info/files to reproduce.

**Comment by martimorta** [comment]
Hi Michael, just tried today after updates, same code on my side and I can see everything 🤷‍♂️ all good!

**Comment by mjeronimo** [comment]
@martimorta Great, glad to hear it.
