### ISSUE TITLE
Path msg orientation error

### ISSUE THREAD

**Issue by BriceRenaudeau** [ros2/rviz#680]
When displaying a `nav_msgs::msg::Path` with `frame_id = "odom"` using "map" as the fixed frame, the orientation of the poses is wrong.
The display depends on the orientation of the "map" frame.

![rviz_path_error2](https://user-images.githubusercontent.com/48433002/117122628-5fddc080-ad96-11eb-8cb4-408849735dc7.png)

![rviz_path_error](https://user-images.githubusercontent.com/48433002/117122613-5d7b6680-ad96-11eb-8cc0-64745d946876.png)

When displaying it in the "odom" frame, they are in the good orientation.

![rviz_path_no_error](https://user-images.githubusercontent.com/48433002/117124250-63724700-ad98-11eb-86d7-e705314fed4a.png)

**Comment by rebecca-butler** [comment]
@BriceRenaudeau could you please provide a code sample to reproduce this issue? Thanks!

**Comment by BriceRenaudeau** [comment]
This simple node publishes a path every 5s.
```c++
class MinimalPub: public rclcpp::Node
{
  public:
    // constructor
    MinimalPub()
    : Node("minimal_publisher"), count(0)
    {
      publisher = this->create_publisher<nav_msgs::msg::Path>("path", rclcpp::QoS(1).transient_local()); // topic latched
      timer_callback();
      timer = this->create_wall_timer(5s, std::bind(&MinimalPub::timer_callback, this));
    }

    //methodes
    void timer_callback()
    {
      auto message = nav_msgs::msg::Path();
      message.header.stamp = now();
      message.header.frame_id = "odom";
      geometry_msgs::msg::PoseStamped pose;
      pose.header.frame_id = "odom";
      for (unsigned int i=0; i<10; i++) {
        pose.pose.position.x += 1.0;
        message.poses.push_back(pose);
      }
      publisher->publish(message);
    }

    // attributes
    rclcpp::TimerBase::SharedPtr timer;
    rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr publisher;
    size_t count;
};
```

Then you can try publishing /TF from map to odom with different orientations.
