### ISSUE TITLE
Feature request: Add support for visualizing YUV image formats

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/rviz#682]
Most cameras in the field output data in YUV formats. It would be nice to add support for visualizing image msgs of YUV formats and not just RGB. This could be implemented by converting YUV to RGB within rviz and then visualizing it.

So if the encoding field in the Image msg is yuv then do the conversion in rviz2 to be able to see the video feed, https://github.com/ros2/common_interfaces/blob/master/sensor_msgs/msg/Image.msg

**Comment by asobhy-qnx** [comment]
@clalancette what do you think of this?

**Comment by clalancette** [comment]
Sure, it seems like a reasonable enough request.  Please feel free to submit a PR for it.

**Comment by asobhy-qnx** [comment]
Great! Yes we can work on it :+1:
