### ISSUE TITLE
Panel close button is missing "X" icon

### ISSUE THREAD

**Issue by clalancette** [ros2/rviz#692]
The upper right-hand corner of every panel in RViz2 has a close button in order to close the panel.  On both Rolling and Galactic, that button exists, but is blank.  That button should have an "X" icon to indicate to the user that this is where it should be closed.

**Comment by Martin-Idel** [comment]
If this is on Windows --> duplicate of https://github.com/ros2/rviz/issues/327, otherwise it's new.

**Comment by clalancette** [comment]
It's on all platforms, though it is probably related.

**Comment by nkalupahana** [comment]
It's blank on foxy macOS as well.
