### ISSUE TITLE
Phantom links in robot_model

### ISSUE THREAD

**Issue by griz1112** [ros2/rviz#695]
I was working with a robot and a zed camera on foxy. Noticed that when I ran the zed camera the links for the robot still showed up in rviz2. Did a reinstall of linux rebuilt foxy so the robot code wasn't on the disk. Rebuilt and ran the zed_wrapper brought up rviz2 robot_model and those links were still there. Very strange. Could be something with robot_state_publisher too hard to  tell.

**Comment by clalancette** [comment]
For questions like this, please as on https://answers.ros.org.  That is our central place for questions and answers, and you are more likely to get an answer there.  If you find that this is truly a bug in rviz or robot_state_publisher, then feel free to open a new issue.

I'm going to close this for now.
