### ISSUE TITLE
Break fork from ros-visualization/rviz if not being reintegrated

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/rviz#699]
Hi,

I wanted to request a fork break (like we did with geometry2 https://github.com/ros2/geometry2/issues/237) so that we can use the GitHub search functionality to find function signatures and quickly track down implementations. With Forks in GitHub, this functionality is disabled and only searches the parent repository. Given that there are some changes, it would be nice if that functionality was restored.

If you email the GitHub folks, they'll sever a fork for you into its same repo, same name, and allows this feature to come back. I did this with slam toolbox and geometry2 without a hitch. 

https://support.github.com/contact

**Comment by clalancette** [comment]
I've now requested GitHub to break the fork.

**Comment by clalancette** [comment]
All right, this has now been done.
