### ISSUE TITLE
[rviz_rendering] render window is black

### ISSUE THREAD

**Issue by greimela** [ros2/rviz#7]
When running the `rendering_example` demo and switching to TAB 2 you only get a black screen instead of a rendered image.

![rviz_rendering-black-screen](https://user-images.githubusercontent.com/11612483/29821151-30fbe95c-8cc7-11e7-8f43-6c2e0f9fbd67.png)

I think this is because auto update is disabled on the `Ogre::RenderWindow`.
Removing `window->setAutoUpdated(false)` from `render_system.cpp:446` should fix this issue.

**Comment by wjwwood** [comment]
This might fix the issue, but I don't think it is the correct solution, since I think the point of that is to have Qt call the ogre `renderOneFrame()` function in its render event. I'll investigate it more.

**Comment by wjwwood** [comment]
Actually you are right. The lines:

```c++
  if (window) {
    window->setActive(true);
    window->setAutoUpdated(false);
  }
```

Are left over from the old rviz code, and the new example from the Ogre wiki (using the QWindow) only sets the window to visible but does not disable auto update or set it active. I'll make a pr to fix this.
