### ISSUE TITLE
Assimp vendor package doesn’t forward assimp::assimp target properly

### ISSUE THREAD

**Issue by wolfv** [ros2/rviz#724]
When assimp is found on the system and is new enough to expose the assimp::assimp new style cmake target, the logic to transform that into an absolute path fails.

Maybe it would be better to either leave it as is or check if there are colons in the name?

**Comment by clalancette** [comment]
I'm pretty sure that this was fixed in #817, so I'm going to close this out.  If not, please feel free to reopen.
