### ISSUE TITLE
libOgreMain.so.1.12.1: undefined reference to `__atomic_fetch_add_8'

### ISSUE THREAD

**Issue by dongpan90** [ros2/rviz#735]
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[5]: *** [Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/build.make:176: bin/OgreXMLConverter] Error 1
make[4]: *** [CMakeFiles/Makefile2:1361: Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/ogre-v1.12.1.dir/build.make:116: ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/ogre-v1.12.1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rviz_ogre_vendor [28min 1s, exited with code 2]

ROS2: 
in the foxy branch

Build system:
Linux raspberrypi 5.10.50-v7l+ #1438 SMP Mon Jul 19 10:46:09 BST 2021 armv7l GNU/Linux

I had did that:
add:  ament_export_library_names(atomic)  in rviz_ogre_vendor/CMakeLists.txt

But, then has these same undefined errors.

**Comment by clalancette** [comment]
Yeah, we don't test on or support armv7l.  So you are on your own here.  If you find a solution, do feel free to open PRs; we are happy to review them.
