### ISSUE TITLE
Can't link with assimp

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros2/rviz#739]
When trying to compile rviz_rendering with the command `colcon build --symlink-install --packages-select rviz_rendering` I get following stacktrace:
```

--- stderr: rviz_rendering
/usr/bin/ld: cannot find -lassimp
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rviz_rendering.dir/build.make:515: librviz_rendering.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:344: CMakeFiles/rviz_rendering.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
```

I am using Ubuntu 20.04 and a ros_rolling master source checkout of ros2.
I have both assimp-utils and assimp-testmodels installed. This is my output for `ls -la | grep assimp`

```
lrwxrwxrwx   1 root root        18 Feb 13  2020 libassimp.so.5 -> libassimp.so.5.0.0
-rw-r--r--   1 root root  12846808 Feb 13  2020 libassimp.so.5.0.0
```

How can I get rviz_rendering to build?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org.  That is our central, searchable site for questions and answers.  When you open your question, please be sure to put a lot of detail in it, including what operating system you are using, what ROS version you are using, and the exact commands you are using that are failing.

I'm going to close this one out.

**Comment by Kaju-Bubanja** [comment]
Deleting the rviz_rendering folder in the build folder and rebuilding the package fixed this error
