### ISSUE TITLE
Missing MeshShape object

### ISSUE THREAD

**Issue by spurnvoj** [ros2/rviz#763]
Hi everyone, I am just trying to migrate our rviz plugins from ROS 1 to ROS 2. I found out that compared to ROS 1 the RVIZ in ROS 2 doesn't have [MeshShape Object](https://github.com/ros-visualization/rviz/blob/noetic-devel/src/rviz/ogre_helpers/mesh_shape.cpp). Is there any reason why this object hasn't been migrated yet?

**Comment by clalancette** [comment]
Just lack of time, I would guess.  If you'd like to contribute it, we'd be happy to review.

**Comment by ctoumieh** [comment]
Hey!
I am migrating a plugin from ROS to ROS2 that uses the MeshShape object. I was wondering if there was any progress on this issue or if @spurnvoj found a workaround.
Thanks.

**Comment by spurnvoj** [comment]
Hi, It is some time back. I solved it by adding MeshShape source and header files into my repo and building it myself. Check the repo here: https://github.com/tiiuae/fog_rviz_plugins

**Comment by ahcorde** [comment]
PR including MeshSahep https://github.com/ros2/rviz/pull/1064

**Comment by ahcorde** [comment]
PR is merged, closing this for now.
