### ISSUE TITLE
Noisy console output when clicking on render panel

### ISSUE THREAD

**Issue by jacobperron** [ros2/rviz#776]
If you start RViz and click in the small space between the 3D render panel and the left panel divider, then we can see a bunch of print statements happening in the console, e.g.:

```
in RenderPanel::mousePressEvent()
in RenderPanel::mouseReleaseEvent()
in RenderPanel::mousePressEvent()
in RenderPanel::mouseReleaseEvent()
in RenderPanel::mouseDoubleClickEvent()
in RenderPanel::mouseReleaseEvent()
in RenderPanel::mousePressEvent()
in RenderPanel::mouseReleaseEvent()
in RenderPanel::mouseDoubleClickEvent()
in RenderPanel::mouseReleaseEvent()
in RenderPanel::mousePressEvent()
in RenderPanel::mouseMoveEvent()
in RenderPanel::mouseMoveEvent()
```

It'd be nice to remove these noisy prints.

**Comment by jacobperron** [comment]
Here's an example of where you can click to reproduce the issue:

![rviz_repro](https://user-images.githubusercontent.com/1218431/135513867-5eef01d6-6833-4e41-bf5d-555470919534.png)

**Comment by ahcorde** [comment]
https://github.com/ros2/rviz/pull/777
