### ISSUE TITLE
STL meshes can't be rendered using WSL2 ROS Galactic Rviz2

### ISSUE THREAD

**Issue by chenjunnn** [ros2/rviz#804]
`rviz2` does not have any error outputs.
![image](https://user-images.githubusercontent.com/57067221/143677854-d556e9a4-e3d3-476e-b063-3985f9b02a87.png)

can't see robot model(stl file) in rviz2, the one can be seen is the collision box:
![image](https://user-images.githubusercontent.com/57067221/143677906-7702375c-67f4-4cd9-9691-c586d2eac64a.png)

when using real ubuntu 20.04 in NUC, it can be shown correctly:
![image](https://user-images.githubusercontent.com/57067221/143836343-7b09e508-81e0-47a9-8f80-e3b03f4e50cc.png)

**Comment by iuhilnehc-ynos** [comment]
There is `a robot model` in the pic.
![image](https://user-images.githubusercontent.com/64191023/143835058-9607bf42-9817-49ee-af75-6a33500ddb9b.png)

but I know that it might be not what you want, could you check your robot model description file?  (or you can upload it if someone wants to help.)

**Comment by chenjunnn** [comment]
@iuhilnehc-ynos This is the collision, not the visual mesh model. Sorry that I forgot to update the expected behavior. And I am quite sure that it is not the urdf problem.

**Comment by iuhilnehc-ynos** [comment]
@sink0918 

I'm not familiar with WSL2. After installing it (Ubuntu20, WSL2, galactic), I [tried to( use `native opengl` also)](https://github.com/microsoft/WSL/issues/4106#issuecomment-876470388) use `rviz2` to show [a demo model](https://docs.ros.org/en/galactic/Tutorials/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html) (without using stl), and it seems to work fine.

![image](https://user-images.githubusercontent.com/64191023/143902575-9e892e8d-7d07-4619-a82c-24f2f7a0511d.png)

Could you confirm whether it can work in your environment? If yes, I'll continue to use another robot `urdf` containing `stl` to debug the rviz2.

**Comment by chenjunnn** [comment]
Basic shapes work fine:
![image](https://user-images.githubusercontent.com/57067221/144037457-291d1ddd-c35d-46f4-9785-5f7f51d6b4d5.png)

The problem seems to be meshes using `stl` or `dae` can not be rendered in rviz2 using WSL2.

By the way, I'm using `WSLg` to use `rviz2`, not `X11-forwarding`.

And I also tried [realsense-description](https://github.com/IntelRealSense/realsense-ros/tree/ros2/realsense2_description), the stl mesh can't be seen either.

**Comment by iuhilnehc-ynos** [comment]
@sink0918 

Thank you for your information, but I'm sorry that I can't reproduce it. (I use windows10 so that I can't use WSLg.)

![image](https://user-images.githubusercontent.com/64191023/144053057-51e4e0bd-cae5-4b7f-a4e9-80d312294815.png)

![image](https://user-images.githubusercontent.com/64191023/144053481-fb94f2bc-b34b-40a4-9286-25557cdf8d54.png)

**Comment by chenjunnn** [comment]
![image](https://user-images.githubusercontent.com/57067221/144214410-75e1fcee-e2e7-4979-a577-1681fd6adbbb.png)

I have tested it using X11-forwarding, but the mesh still can't be rendered😢

Here is some infos of my WSL2:
- Windows Build Number
Microsoft Windows [版本 10.0.22000.194]

- WSL Version
 WSL 2

- Kernel Version
 5.10.16

**Comment by chenjunnn** [comment]
I have also reported this issue to microsoft/WSL, here is the link: https://github.com/microsoft/WSL/issues/7788

**Comment by dpiet** [comment]
I can confirm experiencing this issue as well.

**Comment by ravnicas** [comment]
+1 here, tried on Win11 with iGPU and also nVidia GPU systems.

**Comment by dpiet** [comment]
This appears to still be an issue in rolling, rviz2 v9.1.1. Any ideas what could be the culprit?
It appears to be an issue with WSLg and/or MESA as discussed here: https://github.com/microsoft/wslg/discussions/492
Although not ideal, one workaround is to force software rendering by setting env variable `LIBGL_ALWAYS_SOFTWARE=1`
Hope that helps others.

**Comment by junaidamin** [comment]
Did anyone find a solution to this issue? I am using ROS2 foxy on WSL2 Ubuntu 20.04, and could not see a rendering of either the dae file or stl files. There are no related errors in the terminal. I'm following the tutorial on this page: https://docs.ros.org/en/foxy/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html , where grippers are expected to show up at the end of the red cylinder. Below is my output on RVIZ2:
![image](https://user-images.githubusercontent.com/65314907/221220893-53529083-25c1-4261-b1b2-8373e8997688.png)

**Comment by junaidamin** [comment]
Also, does anyone know why the sphere (head of robot) surface isn't smooth?

**Comment by chenjunnn** [comment]
It works well with ROS2 Humble with WSL Ubuntu 22.04 now.
