### ISSUE TITLE
rviz crashes when leaving fixed frame blank

### ISSUE THREAD

**Issue by relffok** [ros2/rviz#820]
Not a major issue, but if the fixed frame is to be changed and accidentally left blank, rviz terminates immediately if TF is visualized and throwing the error:

```
terminate called after throwing an instance of 'tf2::InvalidArgumentException'
  what():  Invalid argument "" passed to get_latest_common_time - in tf2 frame_ids cannot be empty
Aborted (core dumped)
```

To reproduce:

`rviz2 `

* add TF visualization
* change fixed frame from **map** to blank

**Comment by clalancette** [comment]
Can you give more information about your environment, and how to reproduce this?  I just tried it out locally with Rolling, Galactic, and Foxy, and I couldn't make it crash on any of those.

**Comment by relffok** [comment]
Sure, I'm on Ubuntu 20.04, galactic debian pkgs and rviz is on 8.5.0 (tf2 on 0.17.02 if this is of use)
I was also able to reproduce this on foxy rviz version 8.2.5 (tf2 on 0.13.12)

The steps to reproduce are already mentioned in the initial issue. Any more information needed?

**Comment by clalancette** [comment]
> The steps to reproduce are already mentioned in the initial issue. Any more information needed?

I think it would be helpful to know what you have loaded in RViz2, including the model and any other plugins.  Because I can't make it fail with a simple try here.

**Comment by relffok** [comment]
Like I said in the description, no plugins or anything loaded. 
Anyway after updating the error appears to be gone, I have no clue what caused it. Therefore closing this!
