### ISSUE TITLE
LNK2019 error using VisualizationManager class on Windows

### ISSUE THREAD

**Issue by jonah-gourlay44** [ros2/rviz#856]
I have a class "QtDemo" that has a rviz_common::VisualizationManager* as a private member "manager_". I have a function QtDemo::InitRviz() that initializes the rviz members of the QtDemo class. 
![image](https://user-images.githubusercontent.com/31669911/165804721-018733ff-245a-43e8-ba40-780b701d57b3.png)
When I try to compile this function against either the pre-compiled foxy binaries, or an rviz2 source build, I get the following linker errors:
![image](https://user-images.githubusercontent.com/31669911/165805182-ad26acb8-9e64-4cac-bec0-a79c2e2b93d5.png)
I am linking against

- rviz_common::rviz_common
- rviz_rendering::rviz_rendering
- rviz_ogre_vendor::OgreMain
- rviz_orgre_vendor::OgreOverlay
- Qt5::Core
- Qt5::Widgets

My full [CMakeLists.txt](https://github.com/ros2/rviz/files/8584850/CMakeLists.txt) for reference. For the source build I verified that visualization_manager.cpp was being compiled and that it had the same function definitions. It seems like this is the only file affected, but I can't figure out why. Has anyone seen this before, or have any idea what could be causing it? I am using ROS2 foxy on Windows 10, and doing the source build from the "foxy" development branch.

**Comment by clalancette** [comment]
My best guess here is that VisualizationManager is missing `RVIZ_COMMON_PUBLIC` [here](https://github.com/ros2/rviz/blob/1211b1737a3a4b7f6cd9d148ce073a45059d07bf/rviz_common/include/rviz_common/visualization_manager.hpp#L90).  It would be worthwhile to try adding it to the class and seeing if that makes a difference.  If you can't get that to work, you may instead have to add `RVIZ_COMMON_PUBLIC` to every method inside of the class.

**Comment by jonah-gourlay44** [comment]
> My best guess here is that VisualizationManager is missing `RVIZ_COMMON_PUBLIC` [here](https://github.com/ros2/rviz/blob/1211b1737a3a4b7f6cd9d148ce073a45059d07bf/rviz_common/include/rviz_common/visualization_manager.hpp#L90). It would be worthwhile to try adding it to the class and seeing if that makes a difference. If you can't get that to work, you may instead have to add `RVIZ_COMMON_PUBLIC` to every method inside of the class.

That was it, thank you. The VisualizationManager class just needed the RVIZ_COMMON_PUBLIC macro before it.

**Comment by clalancette** [comment]
> That was it, thank you. The VisualizationManager class just needed the RVIZ_COMMON_PUBLIC macro before it.

If you'd like to open a pull request to add that for future users, we'd be happy to review it.
