### ISSUE TITLE
Rviz: Global Status Error: Fixed frame [map] does not exist; Robot Model Error

### ISSUE THREAD

**Issue by Kushagra-05** [ros2/rviz#890]
I made a **Nav2_Costmap2d plugin** (https://navigation.ros.org/plugin_tutorials/docs/writing_new_costmap2d_plugin.html#tutorial-steps)
& enabled it in **Nav2_params.yaml** as given in doc but when I run turtlebot in Rviz, the output is nowhere like it is mentioned, I don't see any any gradient. 
Moreover, It gives errors like- _Global Status Error: Fixed frame [map] does not exist_ & _Robot Model Error_ 
![Screenshot 2022-08-29 150209](https://user-images.githubusercontent.com/98595254/187195384-0c08f04f-1be0-4ed3-ae00-bfc51b6735ed.png)
The output mentioned in tutorials:
![Screenshot 2022-08-29 172613](https://user-images.githubusercontent.com/98595254/187195688-0d30da5f-45fd-4fef-8d00-849c5699d4b9.png)

**Comment by clalancette** [comment]
For questions about the Navigation2 tutorials, please open an issue on https://github.com/ros-planning/navigation2_tutorials .  If it turns out that this is an issue in RViz itself, then we can reopen the bug.
