### ISSUE TITLE
Build fail with cmake version 3.24.2 (latest)

### ISSUE THREAD

**Issue by manhtoanbkhn** [ros2/rviz#905]
hello,
I get this error:
CMake Error at rviz_ws/install/rviz_rendering/share/rviz_rendering/cmake/ament_cmake_export_targets-extras.cmake:18 (message):
  Failed to find exported target names in
  'rviz_ws/install/rviz_rendering/share/rviz_rendering/cmake/rviz_renderingExport.cmake'
Call Stack (most recent call first):
  rviz_ws/install/rviz_rendering/share/rviz_rendering/cmake/rviz_renderingConfig.cmake:41 (include)
  CMakeLists.txt:35 (find_package)
environment:
ubuntu 22.04
cmake version: 3.24.2
ros2 humble

**Comment by light-tech** [comment]
This is a well-known problem https://github.com/ament/ament_cmake/pull/395

**Comment by clalancette** [comment]
I think this was fixed by https://github.com/ament/ament_cmake/pull/395 , so I'll go ahead and close this.  If you are still having an issue, please feel free to reopen.
