### ISSUE TITLE
rviz_ogre_vendor malformed patch error

### ISSUE THREAD

**Issue by jollypolly123** [ros2/rviz#925]
Not sure if I'm asking in the right place, but hoping I could get some guidance on how to resolve this.

I'm following this guide to setup ROS 2 on MacOS 13.0: https://docs.ros.org/en/humble/Installation/Alternatives/macOS-Development-Setup.html

Running `colcon build --symlink-install --packages-skip-by-dep python_qt_binding` gives me this error so the build fails:
```
patch: **** malformed patch at line 1817: 
make[2]: *** [ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-patch] Error 2
make[1]: *** [CMakeFiles/ogre-v1.12.1.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by clalancette** [comment]
In short, this usually happens when OGRE gets rebuilt for some reason.  You should be able to fix it by doing `rm -rf build/rviz_ogre_vendor install/rviz_ogre_vendor`, and it should then work.

I'm going to close this out, but feel free to reopen if you are still having problems.

**Comment by jacetto** [comment]
I still get the same error, even after removing the build and install dirs

**Comment by openvmp** [comment]
Same here. The problem remains even after removing the build and install dirs.
It happens both with the latest and an old (~6m old) Humble source trees.
It started happening after MacOS (and XCode) were updated.

Please, reopen.

**Comment by openvmp** [comment]
@clalancette , PTAL

**Comment by Kaju-Bubanja** [comment]
Will this be backported to humble?
