### ISSUE TITLE
rviz render lots of points faster question

### ISSUE THREAD

**Issue by peter5232** [ros2/rviz#955]
I want to ask a question. I use glVertex3f when I use the QOpenGLWidget to call the OpenGL command to render the point cloud. But when I render nearly 100 million points, the whole program gets stuck. What measures does Rviz use to render the point cloud, and has it been thinned?

**Comment by clalancette** [comment]
We have not done any performance benchmarking on rviz, no.  If you'd like to do some of that and propose an improvement, we'd be happy to review those.

Since there isn't really an actionable item in here, I'm going to close this for now.  Feel free to reopen if you disagree.
