### ISSUE TITLE
Using service client to get data in rviz2 plguin

### ISSUE THREAD

**Issue by nrasulnrasul** [ros2/rviz#956]
In a custom rviz2 plugin, I try to display data received by client from server.

I got the following error.

```
terminate called after throwing an instance of 'std::runtime_error'
what():  spin_once() called while already spinning
```
My code is similar to the following

[https://github.com/introlab/rtabmap_ros/blob/humble-devel/src/rviz/MapCloudDisplay.cpp#L557](https://github.com/introlab/rtabmap_ros/blob/humble-devel/src/rviz/MapCloudDisplay.cpp#L557)

Is it possible at the moment to use client in rviz plugin to get receive data.

This is related to rviz2 not on user level code.

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

**Comment by nrasulnrasul** [comment]
Did you even read the question ? and look the code in link ?
