### ISSUE TITLE
Is ros2-rviz available on android ?

### ISSUE THREAD

**Issue by lygbuaa** [ros2/rviz#963]
I know there is a ros1 version https://github.com/qiao-tw/rviz-for-android,  Is there any ros2 version for rviz android?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
