### ISSUE TITLE
Error RVIZ extrapolation into the future on the same machine

### ISSUE THREAD

**Issue by nawi-25** [ros2/rviz#973]
I get the following error when trying to view my [RPLidar](https://github.com/babakhani/rplidar_ros2) A2 scan in rviz2. It’s on a differential drive robot controlled using Odrive and ros2 control using [Articulated](https://github.com/joshnewans/articubot_one/tree/humble) Robotics. I am running everything on a laptop, no separate machines, on ROS2 humble. (BTW when I run the lidar and odrive on RPI the error get more often).

It shows perfectly fine when viewing the base_link frame, but with Odom the issue occurs.

The error:
'''
[rviz2-4] [ERROR] [1681401743.264000589] [rviz2]: Lookup would require extrapolation into the future. Requested time 1681401743.323050 but the latest data is at time 1681401743.259460, when looking up transform from frame [laser_frame] to frame [map]
'''

I changed the RPlidar pkg according this [link](https://robotics.stackexchange.com/questions/24036/lookup-would-require-extrapolation-into-the-future-on-the-same-machine), Lookup would require extrapolation into the future on the same machine. It works intermittently but it often loses transform (I often get the error).

i tried to change the update_rate in the controller.yaml for ros2 control, but the issue just get wors.

**Comment by clalancette** [comment]
There is likely some frame in-between the fixed frame and the lidar frame that is not updating at the same rate, so there isn't a full path through the tf tree.  That could cause this error.

In the future, please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
