### ISSUE TITLE
No DepthCloud Display Type in RViZ 2

### ISSUE THREAD

**Issue by zkytony** [ros2/rviz#976]
In RViZ 1, there was a "DepthCloud" display type that allows you to configure an RGB image topic, depth topic, and it automatically visualizes the point cloud. I don't see this in RViZ 2's list of display types.

Is this functionality achievable through some other display types?  Will this display type be added?

**Comment by clalancette** [comment]
In short, we never spent the time to port it over.  If you are interested in doing the port and opening a pull request, we'd be happy to review it.

I'm not sure about other ways to achieve this functionality, but it might be worth asking on https://answers.ros.org .

**Comment by zkytony** [comment]
I would be happy to help in my spare time. Do you have pointers for what to look at to figure out how to port this over?  Thanks

**Comment by clalancette** [comment]
Generally you would look at the code in https://github.com/ros-visualization/rviz/blob/noetic-devel/src/rviz/default_plugin/depth_cloud_display.cpp and https://github.com/ros-visualization/rviz/blob/noetic-devel/src/rviz/default_plugin/depth_cloud_display.h , and figure out a way to make it work with RViz2.  Note that there have been some significant changes between RViz and RViz2, so it may require getting more familiar with the RViz2 APIs.
